In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

# Load the digits dataset
digits = datasets.load_digits()
x, y = digits.data, digits.target
r,c = x.shape

#Dimensions of the dataset
print(f"Shape of dataset': {r} {c}")

# Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Create and train an SVC classifier
classifier = SVC(kernel='linear')
classifier.fit(x_train, y_train)

# Make predictions on the test set
y_pred = classifier.predict(x_test)

# Evaluate the classifier
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

#Accuracy 
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy: ", accuracy)

# Print the number of support vectors for each class
print("\nSupport Vectors:")
print(classifier.support_vectors_)

# Print the total number of support vectors
print(f"Total number of support vectors: {len(classifier.support_vectors_)}")

Shape of dataset': 1797 64
Confusion Matrix:
[[53  0  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  1  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  1 52  0  1  0  0  0  0]
 [ 0  1  0  0 59  0  0  0  0  0]
 [ 0  0  0  0  0 64  0  1  0  1]
 [ 0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  0  0  0  0  1  0  0 42  0]
 [ 0  0  0  0  1  0  0  1  1 56]]

Accuracy:  0.9796296296296296

Support Vectors:
[[ 0.  0.  3. ...  5.  0.  0.]
 [ 0.  0.  0. ...  6.  0.  0.]
 [ 0.  0.  2. ...  1.  0.  0.]
 ...
 [ 0.  0.  2. ... 14. 10.  1.]
 [ 0.  0.  0. ...  7.  0.  0.]
 [ 0.  0.  2. ... 10.  0.  0.]]
Total number of support vectors: 374


In [17]:
import pandas as pd
from sklearn import datasets
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

digits = datasets.load_digits()
x, y = digits.data, digits.target
r, c = x.shape

print(f"Shape of the dataset: {r} {c}")

x_train, x_test, y_train, y_test = train_test_split( x, y, test_size = 0.3, random_state = 42)

model = SVC(kernel = 'linear')
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print(f"Classification Report: \n{classification_report(y_test, y_pred)}")
print(f"Accuracy Score: {accuracy_score(y_test, y_pred)}")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Support Vectors: {model.support_vectors_}")
print(f"Number of support vectors: {len(model.support_vectors_)}")
print(f"Weight: {model.intercept_}")
print(f"Bias : {model.coef_}")

Shape of the dataset: 1797 64
Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       0.98      0.98      0.98        50
           2       0.98      1.00      0.99        47
           3       1.00      0.96      0.98        54
           4       0.98      0.98      0.98        60
           5       0.97      0.97      0.97        66
           6       1.00      1.00      1.00        53
           7       0.96      0.98      0.97        55
           8       0.95      0.98      0.97        43
           9       0.97      0.95      0.96        59

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540

Accuracy Score: 0.9796296296296296
Confusion Matrix: 
[[53  0  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  1  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  1 52  0  1  0  0  0  0]
 